CREATE DATABASE IF NOT EXISTS b4uj3tr63uw1lggdbkz6;

USE b4uj3tr63uw1lggdbkz6;

CREATE TABLE IF NOT EXISTS admins (
    id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO admins (username, pass) VALUES ("admin", '');

CREATE TABLE IF NOT EXISTS judges (
    id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    points INT(3) NOT NULL DEFAULT 0,
    reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (username, points) VALUES ( "Deno Moore", 0);
INSERT INTO users (username, points) VALUES ( "Wolt Wesne", 0);
INSERT INTO users (username, points) VALUES ( "Jonn Osiepe", 0);

INSERT INTO judges (username, pass) VALUES ("judy", 123);